/***********************************************************************************************************************
**
** Library: OpenCTK
**
** Copyright (C) 2025~Present ChengXueWen.
**
** License: MIT License
**
** Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
** documentation files (the "Software"), to deal in the Software without restriction, including without limitation
** the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
** and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
**
** The above copyright notice and this permission notice shall be included in all copies or substantial portions
** of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
** TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
** THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
** CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
** IN THE SOFTWARE.
**
***********************************************************************************************************************/

#pragma once

#include <octk_media_global.hpp>

OCTK_BEGIN_NAMESPACE

namespace media
{

OCTK_MEDIA_API extern const char kVp8CodecName[];
OCTK_MEDIA_API extern const char kVp9CodecName[];
OCTK_MEDIA_API extern const char kAv1CodecName[];
OCTK_MEDIA_API extern const char kH264CodecName[];
OCTK_MEDIA_API extern const char kH265CodecName[];

// RFC 6184 RTP Payload Format for H.264 video
OCTK_MEDIA_API extern const char kH264FmtpProfileLevelId[];
OCTK_MEDIA_API extern const char kH264FmtpLevelAsymmetryAllowed[];
OCTK_MEDIA_API extern const char kH264FmtpPacketizationMode[];

// RFC 7798 RTP Payload Format for H.265 video.
// According to RFC 7742, the sprop parameters MUST NOT be included
// in SDP generated by WebRTC, so for H.265 we don't handle them, though
// current H.264 implementation honors them when receiving
// sprop-parameter-sets in SDP.
OCTK_MEDIA_API extern const char kH265FmtpProfileSpace[];
OCTK_MEDIA_API extern const char kH265FmtpTierFlag[];
OCTK_MEDIA_API extern const char kH265FmtpProfileId[];
OCTK_MEDIA_API extern const char kH265FmtpLevelId[];
OCTK_MEDIA_API extern const char kH265FmtpProfileCompatibilityIndicator[];
OCTK_MEDIA_API extern const char kH265FmtpInteropConstraints[];
OCTK_MEDIA_API extern const char kH265FmtpTxMode[];

} // namespace media

OCTK_END_NAMESPACE